New Release updates
tigrisdata/tigris-docs pull request #247
Opened 2022-12-17 02:44 UTC by icode247

2022-12-20 19:16 UTC, ovaistariq commented on docs/guides/nextjs/_createNextAppOutput
> +$ ➔ npx @tigrisdata/create-tigris-app@beta
This can now be updated to `npx create-tigris-app@latest`

2022-12-20 19:16 UTC, ovaistariq commented on docs/guides/nextjs/index.mdx
> +Tigris uses your project name as the database name of your project, saving the time of having to set one up.
Change this line to:

Every Tigris project comes with a pre-configured database.

2022-12-20 19:21 UTC, ovaistariq commented
Rename `static/img/gifs/what_we_build_result copy.gif` to `static/img/gifs/what_we_build_result.gif`

2022-12-20 19:22 UTC, ovaistariq commented
What do you think about moving the content on this page "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/" to "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/app-with-next/" because they both show how to create a new Next.js app with Tigris.

2022-12-20 19:22 UTC, ovaistariq commented
From `Getting Started` section we can remove the following:
```
Tigris
For macOS: brew install tigrisdata/tigris/tigris-cli
Other operating systems: [See installation instructions here](https://tigris-docs-git-release-updates-tigrisdata.vercel.app/cli/installation)
```

2022-12-20 19:24 UTC, ovaistariq commented
Can you update this guide https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/add-existing-app/ so that the user follows the login/signup, project creation steps similar to what you have at https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/

2022-12-20 20:05 UTC, icode247 commented on docs/guides/nextjs/_createNextAppOutput
> +$ ➔ npx @tigrisdata/create-tigris-app@beta
This was not used, snce the command that creates the project is generated from the console. But I have changed it.

2022-12-20 20:13 UTC, icode247 commented
> What do you think about moving the content on this page "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/" to "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/app-with-next/" because they both show how to create a new Next.js app with Tigris.

"https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/" build new Next.js Tigris applications, while "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/app-with-next/" covers how to add Tigris to an existing Next.js application. I think both have their use cases.

2022-12-20 20:23 UTC, icode247 commented
> 

Based on the new changes, I think "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/" will be removed since the console generates the credentials by default and appends it to the command. So if the user creates a new project, will they ignore the command and locate the credentials so they can provide them when they run the "create-tigris-app" from the terminal to create a project?

2022-12-20 20:27 UTC, icode247 commented
> What do you think about moving the content on this page "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/" to "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/app-with-next/" because they both show how to create a new Next.js app with Tigris.

Yes, you are right. But if we move it there, we may be repeating the same content on a different page.

2022-12-21 08:16 UTC, ovaistariq commented
> > What do you think about moving the content on this page "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/" to "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/app-with-next/" because they both show how to create a new Next.js app with Tigris.
> 
> Yes, you are right. But if we move it there, we may be repeating the same content on a different page. We could remove it.

Yeah you are right, it is better to remove.

2022-12-21 08:18 UTC, ovaistariq commented
> > 
> 
> Based on the new changes, I think "https://tigris-docs-git-release-updates-tigrisdata.vercel.app/guides/nextjs/add-existing-app/" will be removed since the console generates the credentials by default and appends it to the command. So if the user creates a new project, will they ignore the command and locate the credentials so they can provide them when they run the "create-tigris-app" from the terminal to create a project?

If the user is adding Tigris to an existing app, then they will not be using "create-tigris-app", right?

2022-12-21 10:06 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +![create-tigirs-app-command](/img/screenshots/create-tigris-app-command.png)
Can we add a alt text description?

2022-12-21 10:20 UTC, leggetter requested changes
I haven't run through this in order to check it works, but I've added a few recommendations.

2022-12-21 10:20 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +![create-tigirs-app-command](/img/screenshots/create-tigris-app-command.png)
Can we add a better alt text description?

2022-12-21 10:20 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +![created_collections](/img/screenshots/created-collections.png)
Improve alt text

2022-12-21 10:20 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +Here you will find a set of guides to help you quickly build a dynamic data-rich
easily/quicky - do we need either of these words or can it be removed completely?

2022-12-21 10:20 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +Enter `todo` as your project name and click on the `Create` button. Tigris will generate the Cloud credentials for your application with a command to create your application using the credentials.
I don't understand this sentence:

> Tigris will generate the Cloud credentials for your application with a command to create your application using the credentials.

2022-12-21 10:20 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +Now, if you go back to your Tigris console, you should see the collections created for the project.
I'd suggest we avoid words like "should".

We _should_ be confident that things will work. "Should" suggestions there's a scenario where the collections may not be created.

See [this section on avoiding vague and cautious language](https://github.com/ably/docs/blob/main/writing-style-guide.md#avoid-vague-and-cautious-language 
) from a style guide by @tbedford.

2022-12-21 14:23 UTC, icode247 commented on docs/guides/nextjs/index.mdx
> +![created_collections](/img/screenshots/created-collections.png)
Done

2022-12-21 14:23 UTC, icode247 commented on docs/guides/nextjs/index.mdx
> +![create-tigirs-app-command](/img/screenshots/create-tigris-app-command.png)
Done

2022-12-21 14:24 UTC, icode247 commented on docs/guides/nextjs/index.mdx
> +Enter `todo` as your project name and click on the `Create` button. Tigris will generate the Cloud credentials for your application with a command to create your application using the credentials.
Changed "should" to "will"

2022-12-21 14:25 UTC, leggetter requested changes
A few tweaks to ALT text for images and a couple of other small text updates

2022-12-21 14:25 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +![create a new project](/img/screenshots/create-new-project.png)
```suggestion
![The create a project dialog within the Tigris console web application](/img/screenshots/create-new-project.png)
```

2022-12-21 14:25 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +Enter `todo` as your project name and click on the `Create` button. Tigris will generate the Cloud credentials for your application with a command to create your application using the credentials.
```suggestion
Enter `todo` as your project name and click on the `Create` button. Tigris will generate the Cloud credentials for your application. You will also be shown a command to create your application using the credentials.
```

2022-12-21 14:25 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +![create-tigirs-app command](/img/screenshots/create-tigris-app-command.png)
```suggestion
![The create-tigirs-app terminal command displayed within a dialog within the Tigris web console](/img/screenshots/create-tigris-app-command.png)
```

2022-12-21 14:25 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +![Tigris collections](/img/screenshots/created-collections.png)
```suggestion
![The collections for the project within the Tigris web console](/img/screenshots/created-collections.png)
```

2022-12-21 14:25 UTC, leggetter commented on docs/guides/nextjs/index.mdx
> +Here you will find a set of guides to help you quickly build a dynamic data-rich
```suggestion
Here you will find a set of guides to help you build a dynamic data-rich
```

2022-12-21 14:25 UTC, icode247 commented on docs/guides/nextjs/index.mdx
> +Now, if you go back to your Tigris console, you should see the collections created for the project.
Changed "should" to "will"

2022-12-21 14:32 UTC, icode247 commented
@leggetter, I should commit the changes?

2022-12-21 14:54 UTC, leggetter approved these changes

2022-12-21 21:52 UTC, merged