Secondary index docs
tigrisdata/tigris-docs pull request #367
Opened 2023-04-12 14:19 UTC by garrensmith

Documentation for secondary indexes.

Closes #311

2023-04-26 18:04 UTC, ovaistariq commented on docs/concepts/database/indexes.mdx
> +
Do you want to have code sample here as well?

2023-04-26 18:04 UTC, ovaistariq commented on docs/concepts/database/indexes.mdx
> +querying or if the index is still being built:
Briefly describe what you mean by index being built

2023-04-26 18:04 UTC, ovaistariq commented on docs/sdkstools/golang/database/indexes.mdx
> +```
Does the user need to do anything else once they have tagged the field?

2023-04-28 14:58 UTC, ovaistariq approved these changes

2023-05-02 12:40 UTC, leggetter requested changes
It may be worth renaming the `indexes` file to secondary-indexes` do avoid confusion with the files named `index`. `index` is often the entry point to a section in the docs.

I've nitpicked a few `typescript` -> `ts` changes just to be consistent with what I've seen in the docs.

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +and will be used once there are documents in the collection. If this is an existing collection, then you need to log into
How does this work for anyone using the self-hosted version of Tigris where there isn't a console?

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +```typescript
```suggestion
```ts
```

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +`_tigris_updated_at` will return documents in the order they were updated. If a document has not been updated, then the updated field will be null. This index will first return all documents that hav
```suggestion
Tigris has two default indexes created to query a collection by:

 1.  `_tigris_created_at`: When a document was created or when a document was added.  `_tigris_created_at` will return documents in the order they were created, from earliest to last created.
2: `_tigris_updated_at`: When the document was last updated. `_tigris_created_at` will return documents in the order they were updated. If a document has not been updated, the updated field will be `null`. This index will first return all documents that have not been updated, followed by the earliest to latest updated documents
```

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +userCollection.find({ filter: { _tigris_created_at: { $gte: null } } });
What does greater than `null` mean? I'd assume greater than should be used with a number type. Is this common in DBs?

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +```
Suggesting an update so the JSON shown is valid JSON.

```suggestion
that will give more information on the query. The explain query will return
a JSON payload with the following properties:

- `collection`: The collection that the explain response is run against
- `read_type`:  // The Type of read can be either Primary Index scan or Secondary Index. Valid values are `primary index` or `secondary index`
- `filter`: The filter used in the query
- `keyRangeList`: The ranges used to query the index
- `field`: The field used for the query

For example:

```json
{
  collection: "collection name",
  read_type: "primary index",
  filter: {myField: {"$gte": 10}},
  keyRangeList: [ "10", "$TIGRIS_MAX"],
  field: "myField"
}
```
```

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +querying or if the index is still being updated:
```suggestion
An index can be in one of two states depending on whether the index can be used for
querying or if the index is still being updated:
```

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +The index status for indexes can be fetched from the system using the `DescribeCollection`
Where can the reader get more info on `DescribeCollection`?

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +and will be used once there are documents in the collection. If this is an existing collection, then you need to log into
Link to limitations section?

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +## Building indexes in the Web Console
Link to limitations section?

2023-05-02 12:40 UTC, leggetter commented on docs/sdkstools/golang/database/indexes.mdx
> +If you are adding an index to an existing collection, you will need to log into the Tigris web console to initiate a build
Link to limitations section?

2023-05-02 12:40 UTC, leggetter commented on docs/sdkstools/golang/database/indexes.mdx
> +to satisfy the query.
Link to the referenced methods?

2023-05-02 12:40 UTC, leggetter commented on docs/sdkstools/typescript/database/indexes.mdx
> +```typescript showNumbers{4,7}
```suggestion
```ts showNumbers{4,7}
```

2023-05-02 12:40 UTC, leggetter commented on docs/sdkstools/typescript/database/indexes.mdx
> +```typescript
```suggestion
```ts
```

2023-05-02 12:40 UTC, leggetter commented on docs/sdkstools/typescript/database/indexes.mdx
> +When running a `findOne` or `findMany`, Tigris will automatically look to see if a secondary index can be used
Link to referenced methods?

2023-05-02 12:40 UTC, leggetter commented on docs/concepts/database/indexes.mdx
> +Tigris supports adding secondary indexes to fields in a collection. Adding an index to a field will allow for
Does this go into enough detail regarding explaining what a secondary index is? Are we assuming too much knowledge?

2023-05-03 14:44 UTC, garrensmith commented on docs/concepts/database/indexes.mdx
> +and will be used once there are documents in the collection. If this is an existing collection, then you need to log into
This is temporary and will go away soon. So for self-hosted there is an endpoint a user could use. but we don't want to advertise that endpoint to much.

2023-05-03 14:51 UTC, garrensmith commented on docs/concepts/database/indexes.mdx
> +userCollection.find({ filter: { _tigris_created_at: { $gte: null } } });
This is common. This is find me all the documents in that index.

2023-05-03 14:56 UTC, garrensmith commented on docs/concepts/database/indexes.mdx
> +The index status for indexes can be fetched from the system using the `DescribeCollection`
This is missing. We need a section on the collection operations a SDK can do

2023-05-03 14:59 UTC, garrensmith commented on docs/sdkstools/golang/database/indexes.mdx
> +to satisfy the query.
How would I do that?

2023-05-03 15:18 UTC, garrensmith commented
@leggetter I've updated this PR with most the fixes you recommended. I've also added a section explaining how the querying and filtering works.

2023-05-08 21:49 UTC, ovaistariq commented on docs/sdkstools/golang/database/secondary-indexes.mdx
> +An index can be in `INDEX ACTIVE` state which means the index is being used for queries or in `INDEX WRITE MODE` where the index is
@garrensmith do we need to update this with the additional state that you have added?

2023-05-08 21:50 UTC, ovaistariq approved these changes

2023-05-09 13:24 UTC, garrensmith commented on docs/sdkstools/golang/database/secondary-indexes.mdx
> +An index can be in `INDEX ACTIVE` state which means the index is being used for queries or in `INDEX WRITE MODE` where the index is
Yes. Just updated it.

2023-05-09 14:48 UTC, leggetter requested changes
One typo and a few suggestions.

2023-05-09 14:48 UTC, leggetter commented on docs/concepts/database/secondary-indexes.mdx
> +on one of the fields in the filter will improve the performance of that query by because Tigris can use that field to efficiently
```suggestion
on one of the fields in the filter will improve the performance of that query because Tigris can use that field to efficiently
```

2023-05-09 14:48 UTC, leggetter commented on docs/concepts/database/secondary-indexes.mdx
> +like `$gte` when reading from the secondary index. Using the `name` query, it will retrieve documents with id `1` and `3`. Document with id `2`, does not have a
```suggestion
like `$gte` when reading from the secondary index. Using the `name` query, it will retrieve documents with id `1` and `3`. Document with id `2` does not have a
```

2023-05-09 14:48 UTC, leggetter commented on docs/concepts/database/secondary-indexes.mdx
> +Currently, only a single index is supported for sorting.
How is this set? Code examples and JSON payloads have been shared above, which makes the absence here more noticeable.

2023-05-09 14:48 UTC, leggetter commented on docs/concepts/database/secondary-indexes.mdx
> +2. Indexes can only be built for existing collections via the web-console
```suggestion
2. Indexes can only be built for existing collections via the Web Console
```

Consistent naming. We're not consistent generally, so just being consistent in this single doc is a good step forward :)

2023-05-09 14:48 UTC, leggetter commented on docs/sdkstools/typescript/database/secondary-indexes.mdx
> +When running a `findOne` or `findMany`, Tigris will automatically look to see if a secondary index can be used
We're referencing functions but not providing a link to where to find out more about those functions or how they can be used in general. Here's an example of what I'm suggesting for this doc and the Go one as I think it's good practice and provides a better DX.

```suggestion
When running a [`findOne`](/docs/sdkstools/typescript/database/query/#find-one) or [`findMany`](/docs/sdkstools/typescript/database/query/#find-many), Tigris will automatically look to see if a secondary index can be used
```

2023-05-09 14:48 UTC, leggetter commented on docs/sdkstools/typescript/database/secondary-indexes.mdx
> +When running a `findOne` or `findMany`, Tigris will automatically look to see if a secondary index can be used
To achieve this with the Go docs, they would need to be refactored to allow individual functions to be referenced. This would be a good thing.

2023-05-09 14:48 UTC, leggetter commented on docs/sdkstools/typescript/database/secondary-indexes.mdx
> +## Querying, sorting and explain
Is there a reason these are in the same heading rather than split out into three separate headings?

If they are split out, i make it:

1. Easier to quickly reference via skimming
2. Linkable both in the in-page ToC, but also from another page or anywhere else on the web

2023-05-09 14:48 UTC, leggetter commented on docs/sdkstools/typescript/database/secondary-indexes.mdx
> +## Querying, sorting and explain
Same comment on the Go docs.

2023-05-10 15:22 UTC, leggetter commented on docs/sdkstools/golang/database/secondary-indexes.mdx
> +## Sorting
Nit: Headings are `Query` and `Sort` in the TypeScript version.

2023-05-10 15:22 UTC, leggetter approved these changes

2023-05-10 16:35 UTC, merged