update http quickstart with working api urls
tigrisdata/tigris-docs pull request #375
Opened 2023-04-20 03:41 UTC by ibrahim-akrab

This PR closes #316 

I found the search section not applicable without an index so I got rid of it. An alternative would have been creating the index but it is the same steps as creating a collection and it seemed very repetitive. I can add the necessary steps to create the index and search if needed.

/claim #316

2023-04-20 19:52 UTC, ibrahim-akrab commented
I'll prettify it and try again

2023-04-20 19:52 UTC, ibrahim-akrab commented
I'll prettify it and try again

2023-04-20 19:53 UTC, ovaistariq requested changes

2023-04-20 19:53 UTC, ovaistariq commented on docs/quickstarts/quickstart-http.mdx
> +curl https://api.preview.tigrisdata.cloud/v1/projects/quickstart/database/collections/users/createOrUpdate \
Could you update the schema below to demonstrate making `name` searchable?

```
"balance": {
              "type": "number",
              "searchIndex": true
            },
"name": {
              "type": "string",
              "searchIndex": true
            }
```

2023-04-20 19:53 UTC, ovaistariq commented on docs/quickstarts/quickstart-http.mdx
> +curl https://api.preview.tigrisdata.cloud/v1/projects/quickstart/database/collections/users/createOrUpdate \
Then once you have done that, you can add an API example for making a search request on the `name` field.

2023-04-20 19:53 UTC, ovaistariq commented on docs/quickstarts/quickstart-http.mdx
> -### Search
Check my comment above. Once you have updated the schema to mark fields as searchable, this API request will start to work.

2023-04-20 19:57 UTC, ibrahim-akrab commented on docs/quickstarts/quickstart-http.mdx
> +curl https://api.preview.tigrisdata.cloud/v1/projects/quickstart/database/collections/users/createOrUpdate \
Sure thing. Will update it and check the full quickstart.

2023-04-20 20:31 UTC, ibrahim-akrab commented
@ovaistariq It should be all good now.

I'd like to mention something I noticed while updating this quickstart. The application key created by the CLI registers on the web interface, however, it doesn't generate an access token reliably. I've tried creating the key using the web interface then generating the access token using the CLI and it works flawlessly.

2023-04-21 01:22 UTC, ovaistariq commented
> @ovaistariq It should be all good now.
> 
> I'd like to mention something I noticed while updating this quickstart. The application key created by the CLI registers on the web interface, however, it doesn't generate an access token reliably. I've tried creating the key using the web interface then generating the access token using the CLI and it works flawlessly. When the CLI fails, it returns `{"error":{"code":"UNAUTHENTICATED","message":"Invalid credentials"}}`

Thanks for letting me know about this. So if I understand correctly, if the application key is created using CLI, then the token mechanism doesn't work reliably. But if the application key is created using the web console then everything work as expected?

2023-04-21 01:25 UTC, ovaistariq approved these changes

2023-04-21 01:25 UTC, merged

2023-04-21 02:33 UTC, ibrahim-akrab commented
@ovaistariq Yes, that's what happens.

2023-04-24 14:55 UTC, TheLazyIndianTechie commented
Yup, I have the same issue. Let me try the fix @ibrahim-akrab has mentioned.

2023-05-27 03:02 UTC, ovaistariq commented
There were a couple more fixes that I have done on the HTTP quickstart. Let me know if you still run into issues: https://www.tigrisdata.com/docs/quickstarts/quickstart-http/